version: "3.9"
services:
  php-apache:
    ports:
      - "80:80"
    build: './docker/php'
    volumes:
      - .:/var/www/html/modulePHP/projet_php/
  mysql:
    ports:
      - "3306:3306"
    build: './docker/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "reseau_social0"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: